apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellojava-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellojava
  template:
    metadata:
      labels:
        app: hellojava
    spec:
      containers:
      - name: hellojava
        image: pavankumarsangisetti/hellojava:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
